# -*- coding: utf-8 -*-
"""SupplementScheduerWebsiteCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLl3w1ZppEvO2qELQ-A7vZqbtju_CcVq
"""

import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
import tempfile

# CONFIG
st.set_page_config(
    page_title="Supplement Scheduler",
    layout="wide"
)

# LOAD DATA
@st.cache_data
def load_data():
    return pd.read_excel("/content/Vitamin_RuleModel_Output (6).xlsx")

df = load_data()

st.title("💊 Supplement Scheduler")
st.caption("Rule‑based scheduling using manufacturer directions")

# USER PROFILE
st.sidebar.header("Your Daily Routine")

wake_time = st.sidebar.time_input("Wake time", value=datetime.strptime("07:00", "%H:%M").time())
breakfast = st.sidebar.time_input("Breakfast", value=datetime.strptime("08:00", "%H:%M").time())
lunch = st.sidebar.time_input("Lunch", value=datetime.strptime("13:00", "%H:%M").time())
dinner = st.sidebar.time_input("Dinner", value=datetime.strptime("19:00", "%H:%M").time())
bed_time = st.sidebar.time_input("Bedtime", value=datetime.strptime("22:30", "%H:%M").time())

# SUPPLEMENT SELECTION
st.header("Select Supplements")

supplement_names = sorted(df["Product Name"].dropna().unique())
chosen = st.multiselect("Choose supplements", supplement_names)

chosen_df = df[df["Product Name"].isin(chosen)].copy()

# HELPERS
def compute_timing(row):
    if row.get("bedtime"):
        return "Bedtime"
    if row.get("morning"):
        return "Morning"
    if row.get("empty_stomach"):
        return "Empty stomach"
    if row.get("with_food"):
        return "With meals"
    return "Anytime"

def timing_to_clock(timing):
    if timing == "Morning":
        return wake_time
    if timing == "With meals":
        return breakfast
    if timing == "Empty stomach":
        return (datetime.combine(datetime.today(), breakfast) - timedelta(minutes=30)).time()
    if timing == "Bedtime":
        return (datetime.combine(datetime.today(), bed_time) - timedelta(minutes=30)).time()
    return wake_time

# CYCLE LOGIC
st.header("Cycle Settings")

use_cycle = st.checkbox("Enable cycle (30 days on / 7 days off)", value=True)
cycle_start = st.date_input("Cycle start date", datetime.today())

def is_on_cycle(date):
    if not use_cycle:
        return True
    delta = (date - cycle_start).days
    cycle_day = delta % 37
    return cycle_day < 30

today = datetime.today().date()
on_cycle_today = is_on_cycle(today)

if not on_cycle_today:
    st.warning("❌ Today is an OFF‑cycle day. No supplements scheduled.")
    st.stop()

# DOSING CONTROLS
st.header("Dosage & Timing")

schedule_rows = []

for _, row in chosen_df.iterrows():
    st.subheader(row["Product Name"])

    min_dose = row.get("daily_dose_min", 1)
    max_dose = row.get("daily_dose_max", min_dose)

    dose = st.number_input(
        "Daily dose",
        min_value=float(min_dose),
        max_value=float(max_dose),
        value=float(min_dose),
        key=f"dose_{row['Product Name']}"
    )

    timing = compute_timing(row)
    time_of_day = timing_to_clock(timing)

    if row.get("max_warning"):
        st.warning("⚠ Do not exceed recommended daily amount")

    if row.get("caffeine_warning"):
        st.warning("⚠ Avoid caffeine")

    schedule_rows.append({
        "Supplement": row["Product Name"],
        "Dose": dose,
        "Timing": timing,
        "Time": time_of_day.strftime("%H:%M"),
        "Instructions": row.get("suggested_use_clean", "")
    })

# SCHEDULE DISPLAY
schedule_df = pd.DataFrame(schedule_rows)
if not schedule_df.empty:
    schedule_df = schedule_df.sort_values("Time")

st.header("📅 Today's Schedule")
st.dataframe(schedule_df, width='stretch')

# PDF GENERATION
def generate_pdf(schedule_df):
    file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    c = canvas.Canvas(file.name, pagesize=LETTER)
    width, height = LETTER

    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 40, "Daily Supplement Schedule")

    c.setFont("Helvetica", 10)
    y = height - 80

    for _, row in schedule_df.iterrows():
        text = f"{row['Time']} — {row['Supplement']} ({row['Dose']})"
        c.drawString(40, y, text)
        y -= 15

        if row["Instructions"]:
            c.setFont("Helvetica-Oblique", 9)
            c.drawString(60, y, row["Instructions"][:90])
            c.setFont("Helvetica", 10)
            y -= 20

        if y < 80:
            c.showPage()
            y = height - 80

    c.save()
    return file.name

st.header("📄 Export")

if st.button("Download PDF Schedule"):
    pdf_path = generate_pdf(schedule_df)
    with open(pdf_path, "rb") as f:
        st.download_button(
            "Download PDF",
            f,
            file_name="supplement_schedule.pdf",
            mime="application/pdf"
        )

# DISCLAIMER
st.divider()
st.caption(
    "⚠ This tool follows manufacturer label instructions only. "
    "It does not provide medical advice. Consult a healthcare professional before use."
)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# !streamlit run app.py
#
